#
# Travis Setup
#

# use ubuntu trusty for newer version of nodejs, used for JS testing
dist: trusty

# faster builds on new travis setup not using sudo
sudo: false


#
# Test Matrix
#

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly
